# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Analog_Pins.xdc

# Block Designs: bd/SABER/SABER.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER || ORIG_REF_NAME==SABER} -quiet] -quiet

# IP: bd/SABER/ip/SABER_wifi_pack_reg_0_0/SABER_wifi_pack_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_wifi_pack_reg_0_0 || ORIG_REF_NAME==SABER_wifi_pack_reg_0_0} -quiet] -quiet

# IP: bd/SABER/ip/SABER_ADC_8_bits_0_1/SABER_ADC_8_bits_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_ADC_8_bits_0_1 || ORIG_REF_NAME==SABER_ADC_8_bits_0_1} -quiet] -quiet

# IP: bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_axi_gpio_0_0 || ORIG_REF_NAME==SABER_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SABER/ip/SABER_processing_system7_0_0/SABER_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_processing_system7_0_0 || ORIG_REF_NAME==SABER_processing_system7_0_0} -quiet] -quiet

# IP: bd/SABER/ip/SABER_proc_sys_reset_0_0/SABER_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_proc_sys_reset_0_0 || ORIG_REF_NAME==SABER_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/SABER/ip/SABER_axi_smc_0/SABER_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_axi_smc_0 || ORIG_REF_NAME==SABER_axi_smc_0} -quiet] -quiet

# IP: bd/SABER/ip/SABER_encryptor_system_0_1/SABER_encryptor_system_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SABER_encryptor_system_0_1 || ORIG_REF_NAME==SABER_encryptor_system_0_1} -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/SABER_ooc.xdc
