# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.srcs/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/SABER_ADC_8_bits_0_1.xci
# IP: The module: 'SABER_ADC_8_bits_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_xadc_wiz_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_0_0/ADC_8_bits_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_0_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlslice_0_0/ADC_8_bits_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlslice_0_0 || ORIG_REF_NAME==ADC_8_bits_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_1_0/ADC_8_bits_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_1_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_2_0/ADC_8_bits_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_2_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_2_0} -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0_ooc.xdc

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_ADC_8_bits_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.srcs/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/SABER_ADC_8_bits_0_1.xci
# IP: The module: 'SABER_ADC_8_bits_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_xadc_wiz_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_0_0/ADC_8_bits_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_0_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlslice_0_0/ADC_8_bits_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlslice_0_0 || ORIG_REF_NAME==ADC_8_bits_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_1_0/ADC_8_bits_xlconstant_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_1_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xlconstant_2_0/ADC_8_bits_xlconstant_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_8_bits_xlconstant_2_0 || ORIG_REF_NAME==ADC_8_bits_xlconstant_2_0} -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0_ooc.xdc

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_xadc_wiz_0_0/ADC_8_bits_xadc_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_8_bits_clk_wiz_0_0 || ORIG_REF_NAME==ADC_8_bits_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_clk_wiz_0_0/ADC_8_bits_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_ADC_8_bits_0_1/src/ADC_8_bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_ADC_8_bits_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
