# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.srcs/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0.xci
# IP: The module: 'SABER_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.srcs/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0.xci
# IP: The module: 'SABER_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cncai/Desktop/EMSE/AMD/Final_Files/SABER/SABER.gen/sources_1/bd/SABER/ip/SABER_axi_gpio_0_0/SABER_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SABER_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
